# Умножение матриц

In [1]:
import numpy as np

In [7]:
# создадим рандомные матрицы размером 3х3 
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

print('A:\n', A)
print('B:\n', B)

A:
 [[11  5  6]
 [ 5  8  8]
 [ 9 11  9]]
B:
 [[ 1 -2  3]
 [ 1  2  3]
 [ 1  0 -2]]


При таком способе создания получаем матрицы типа ndarray (удобен для работы с многомерными массивами)

In [9]:
print(type(A))

<class 'numpy.ndarray'>


При использовании оператора звёздочка (*) получаем матрицу поэлементного умножения 

In [8]:
A*B

array([[ 11, -10,  18],
       [  5,  16,  24],
       [  9,   0, -18]])

Поменяем тип матриц на np.matrix (частный случай ndarray для работы с двумерными массивами), такие матрицы звёздочкой перемножаются по правилам матричного умножения

In [10]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)

print(A_m*B_m)

[[ 22 -12  36]
 [ 21   6  23]
 [ 29   4  42]]


Матрицы типа ndarray перемножить можно командой dot или оператором @ 

In [11]:
# Матричное умножение
np.dot(A,B)

array([[ 22, -12,  36],
       [ 21,   6,  23],
       [ 29,   4,  42]])

In [12]:
# Матричное умножение
A@B

array([[ 22, -12,  36],
       [ 21,   6,  23],
       [ 29,   4,  42]])

### Порядок умножения 

In [13]:
# Порядок умножения AB != BA
B@A

array([[ 28,  22,  17],
       [ 48,  54,  49],
       [ -7, -17, -12]])

Важно учитывать размерность матриц

In [14]:
# создадим новые матрицы разных размеров
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))

print('A:\n',A)
print('B:\n',B)

A:
 [[ 7  8  7  7  5]
 [ 8  7  9  7  5]
 [ 9  9  7  8 10]]
B:
 [[-1  1]
 [ 1 -1]
 [ 2  2]
 [ 0  3]
 [ 3  0]]


In [15]:
# в таком порядке умножение возможно, 
# т.к. кол-во стобцов А совпадает с кол-вом строк В
A@B

array([[30, 34],
       [32, 40],
       [44, 38]])

In [16]:
# в этом порядке умножение невозможно
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Размер итоговой матрицы - столбцов столько же, сколько в левой матрице, строк - в правой: 

In [17]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


Если матрицы одинакового размера, при изменении порядка умножения итоговые матрицы будут разные

### Умножение на специальные матрицы

In [18]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])

print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-1  2 -4 -2]
 [-3 -4  2 -3]
 [ 2 -2 -2 -3]
 [ 2 -2  3  3]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-1  4  0  2]
 [-3 -8  0  3]
 [ 2 -4  0  3]
 [ 2 -4  0 -3]]
DA:
 [[-1  2 -4 -2]
 [-6 -8  4 -6]
 [ 0  0  0  0]
 [-2  2 -3 -3]]


На диагональную матрицу умножение возможно в любом порядке, но итоговые матрицы разные.

### Умножение на одномерный массив numpy

In [19]:
# умножение матрицы на вектор
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b # важен прядок умножения
# переводить в столбец не нужно, Python делает это сам 

array([2, 6])

In [20]:
b@A # в этом порядке умножение невозможно

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## Матрицы Грама

In [21]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1]) # создадим 3 вектора
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z]) # запишем их в матрицу по строкам
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


Чтобы записать векторы в матрицу по столбцам - транспонируем (A=np.array([x,y,z]).T)

In [22]:
# вычисляем матрицу Грама
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

Получившая матрица - диагональная, значит, векторы ортогональны (образуют ортогональную систему векторов)

In [23]:
# нормируем векторы
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
# составим из нормированных векторов матрицу 
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [24]:
# для нормированной матрицы вычислим матрицу Грама
A_norm@A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Системы векторов, у которых получаются единичные матрицы Грама, называются ОРТОНОРМИРОВАННЫМИ 

Иногда при нормировании вместо нулей получаются числа близкие к 0 (4.58633852е-19), это происходит из=за точности машинного вычисления. В таких случаях нужно округлить числа (np.round(A_norm@A_norm.T,1))

### ортонормированные системы рулят! :)